@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
<<<<<<< HEAD
REM Generated by Vivado on Tue Dec 20 21:34:39 +0800 2022
=======
REM Generated by Vivado on Sat Dec 24 19:50:04 +0800 2022
>>>>>>> da2b0dd963a0f4c07c08133c48869fa3bb87fc84
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
<<<<<<< HEAD
echo "xsim tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view C:/Users/Administrator/Desktop/hardware_project-master/vivado/lab4/project_1/project_1.srcs/sim_1/imports/lab4/tb_top_behav.wcfg -log simulate.log"
call xsim  tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view C:/Users/Administrator/Desktop/hardware_project-master/vivado/lab4/project_1/project_1.srcs/sim_1/imports/lab4/tb_top_behav.wcfg -log simulate.log
=======
echo "xsim tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view C:/Users/xc/Desktop/hard/hardware/vivado/lab4/project_1/project_1.srcs/sim_1/imports/lab4/tb_top_behav.wcfg -log simulate.log"
call xsim  tb_top_behav -key {Behavioral:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view C:/Users/xc/Desktop/hard/hardware/vivado/lab4/project_1/project_1.srcs/sim_1/imports/lab4/tb_top_behav.wcfg -log simulate.log
>>>>>>> da2b0dd963a0f4c07c08133c48869fa3bb87fc84
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
